//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderActivity
    {
        public OrderActivity()
        {
            this.OrderInputs = new HashSet<OrderInput>();
            this.OrderOutputs = new HashSet<OrderOutput>();
        }
    
        public int OrderActivityId { get; set; }
        public int OrderId { get; set; }
        public int ActivityId { get; set; }
        public int ManufacturerId { get; set; }
        public Nullable<int> NextOrderActivityId { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderInput> OrderInputs { get; set; }
        public virtual ICollection<OrderOutput> OrderOutputs { get; set; }
    }
}
