//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderInputs = new HashSet<OrderInput>();
            this.OrderOutputs = new HashSet<OrderOutput>();
            this.ProductSizes = new HashSet<ProductSize>();
            this.ProductStores = new HashSet<ProductStore>();
            this.ProductUoMs = new HashSet<ProductUoM>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public bool ProducyIsActive { get; set; }
        public string Color { get; set; }
        public bool IsInput { get; set; }
        public bool IsFinished { get; set; }
        public string Vendor { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual ICollection<OrderInput> OrderInputs { get; set; }
        public virtual ICollection<OrderOutput> OrderOutputs { get; set; }
        public virtual ICollection<ProductSize> ProductSizes { get; set; }
        public virtual ICollection<ProductStore> ProductStores { get; set; }
        public virtual ICollection<ProductUoM> ProductUoMs { get; set; }
    }
}
