//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        public UnitOfMeasure()
        {
            this.OrderInputs = new HashSet<OrderInput>();
            this.OrderInputs1 = new HashSet<OrderInput>();
            this.OrderOutputs = new HashSet<OrderOutput>();
            this.ProductUoMs = new HashSet<ProductUoM>();
        }
    
        public int UoMId { get; set; }
        public string UoMName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual ICollection<OrderInput> OrderInputs { get; set; }
        public virtual ICollection<OrderInput> OrderInputs1 { get; set; }
        public virtual ICollection<OrderOutput> OrderOutputs { get; set; }
        public virtual ICollection<ProductUoM> ProductUoMs { get; set; }
    }
}
